-- ==========================
-- TENSURA SUPABASE SETUP
-- Chạy trong Supabase SQL Editor (Project mới)
-- ==========================

-- 1) BẢNG NGƯỜI CHƠI
create table if not exists public.tensura_players (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  server_id text not null,
  is_admin boolean default false,
  is_banned boolean default false,
  last_active bigint default 0,
  save_data jsonb,
  mailbox jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_tensura_players_server_id on public.tensura_players(server_id);
create index if not exists idx_tensura_players_last_active on public.tensura_players(last_active desc);

-- 2) BẢNG PVP BATTLE
create table if not exists public.tensura_battles (
  id bigint generated by default as identity primary key,
  server_id text not null,
  challenger text not null,
  target text not null,
  status text not null,
  winner text,
  turn text,
  logs jsonb default '[]'::jsonb,
  p1_hp bigint, p1_max_hp bigint,
  p2_hp bigint, p2_max_hp bigint,
  created_at timestamptz default now()
);

create index if not exists idx_tensura_battles_server on public.tensura_battles(server_id);
create index if not exists idx_tensura_battles_challenger on public.tensura_battles(challenger);
create index if not exists idx_tensura_battles_target on public.tensura_battles(target);

-- 3) BẢNG WORLD CHAT
create table if not exists public.tensura_world_chat (
  id bigint generated by default as identity primary key,
  server_id text not null,
  username text not null,
  content text not null,
  is_admin boolean default false,
  timestamp bigint not null,
  created_at timestamptz default now()
);

create index if not exists idx_tensura_world_chat_server_ts on public.tensura_world_chat(server_id, timestamp);

-- 4) BẬT RLS + POLICY ALLOW-ALL (để anon key CRUD được)
alter table public.tensura_players enable row level security;
alter table public.tensura_battles enable row level security;
alter table public.tensura_world_chat enable row level security;

drop policy if exists "allow_all" on public.tensura_players;
create policy "allow_all" on public.tensura_players for all using (true) with check (true);

drop policy if exists "allow_all" on public.tensura_battles;
create policy "allow_all" on public.tensura_battles for all using (true) with check (true);

drop policy if exists "allow_all" on public.tensura_world_chat;
create policy "allow_all" on public.tensura_world_chat for all using (true) with check (true);

-- 5) GRANT QUYỀN CHO API ROLES
grant usage on schema public to anon, authenticated;
grant all on table public.tensura_players, public.tensura_battles, public.tensura_world_chat to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- 6) REALTIME (publication) + replica identity (để nhận UPDATE đầy đủ)
alter table if exists public.tensura_players replica identity full;
alter table if exists public.tensura_battles replica identity full;
alter table if exists public.tensura_world_chat replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.tensura_players;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.tensura_battles;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.tensura_world_chat;
exception when duplicate_object then null;
end $$;
