
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { SaveData, UserProfile, Mail, BattleState, GAME_SERVERS, Character } from '../types';

export interface WorldChatMessage {
  id: number;
  server_id: string;
  username: string;
  content: string;
  is_admin: boolean;
  timestamp: number;
}

// ==========================================
// CẤU HÌNH SUPABASE
// ==========================================
// Vite sẽ chỉ expose biến môi trường bắt đầu bằng VITE_
// Điền 2 biến này trong file .env.local:
//   VITE_SUPABASE_URL=
//   VITE_SUPABASE_ANON_KEY=
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// SQL CHUẨN ĐỂ TẠO BẢNG (CHẠY 1 LẦN TRONG SUPABASE SQL EDITOR)
// NOTE: Đây là cấu hình “cho chạy nhanh” (policy allow-all) vì game đang dùng anon key trực tiếp.
// Nếu bạn định public game, nên tách backend hoặc siết policy + không lưu password dạng plain text.
const DB_SETUP_SQL = `
-- ==========================
-- TENSURA SUPABASE SETUP
-- Chạy trong Supabase SQL Editor (Project mới)
-- ==========================

-- 1) BẢNG NGƯỜI CHƠI
create table if not exists public.tensura_players (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  server_id text not null,
  is_admin boolean default false,
  is_banned boolean default false,
  last_active bigint default 0,
  save_data jsonb,
  mailbox jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_tensura_players_server_id on public.tensura_players(server_id);
create index if not exists idx_tensura_players_last_active on public.tensura_players(last_active desc);

-- 2) BẢNG PVP BATTLE
create table if not exists public.tensura_battles (
  id bigint generated by default as identity primary key,
  server_id text not null,
  challenger text not null,
  target text not null,
  status text not null,
  winner text,
  turn text,
  logs jsonb default '[]'::jsonb,
  p1_hp bigint, p1_max_hp bigint,
  p2_hp bigint, p2_max_hp bigint,
  created_at timestamptz default now()
);

create index if not exists idx_tensura_battles_server on public.tensura_battles(server_id);
create index if not exists idx_tensura_battles_challenger on public.tensura_battles(challenger);
create index if not exists idx_tensura_battles_target on public.tensura_battles(target);

-- 3) BẢNG WORLD CHAT
create table if not exists public.tensura_world_chat (
  id bigint generated by default as identity primary key,
  server_id text not null,
  username text not null,
  content text not null,
  is_admin boolean default false,
  timestamp bigint not null,
  created_at timestamptz default now()
);

create index if not exists idx_tensura_world_chat_server_ts on public.tensura_world_chat(server_id, timestamp);

-- 4) BẬT RLS + POLICY ALLOW-ALL (để anon key CRUD được)
alter table public.tensura_players enable row level security;
alter table public.tensura_battles enable row level security;
alter table public.tensura_world_chat enable row level security;

drop policy if exists "allow_all" on public.tensura_players;
create policy "allow_all" on public.tensura_players for all using (true) with check (true);

drop policy if exists "allow_all" on public.tensura_battles;
create policy "allow_all" on public.tensura_battles for all using (true) with check (true);

drop policy if exists "allow_all" on public.tensura_world_chat;
create policy "allow_all" on public.tensura_world_chat for all using (true) with check (true);

-- 5) GRANT QUYỀN CHO API ROLES
grant usage on schema public to anon, authenticated;
grant all on table public.tensura_players, public.tensura_battles, public.tensura_world_chat to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- 6) REALTIME (publication) + replica identity (để nhận UPDATE đầy đủ)
alter table if exists public.tensura_players replica identity full;
alter table if exists public.tensura_battles replica identity full;
alter table if exists public.tensura_world_chat replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.tensura_players;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.tensura_battles;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.tensura_world_chat;
exception when duplicate_object then null;
end $$;
`;

class AuthService {
    private supabase: SupabaseClient | null = null;
    private serverId = 'sv1';
    private listeners: Function[] = [];
    private chatSubscription: any = null;
    private battleSubscription: any = null;

    constructor() {
        const savedServer = localStorage.getItem('tensura_selected_server');
        if (savedServer) this.serverId = savedServer;

        if (!SUPABASE_URL || !SUPABASE_KEY) {
            console.warn("Chưa cấu hình Supabase URL/KEY trong authService.ts");
        } else {
            this.supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
            console.log("Supabase Client Initialized");
        }
    }

    setServer(id: string) {
        this.serverId = id;
        localStorage.setItem('tensura_selected_server', id);
    }

    getServerId() { return this.serverId; }
    
    getServerName() {
        return GAME_SERVERS.find(s => s.id === this.serverId)?.name || 'Unknown Server';
    }

    getDatabaseSetupSQL() { return DB_SETUP_SQL; }

    async checkConnection() {
        if (!this.supabase) return { online: false, message: 'Chưa điền API Key Supabase trong code.' };
        try {
            const { count, error } = await this.supabase.from('tensura_players').select('*', { count: 'exact', head: true });
            if (error) throw error;
            return { online: true, message: 'Connected to Supabase' };
        } catch (e: any) {
            console.error("Supabase Connection Error:", e);
            return { online: false, message: 'Lỗi kết nối: ' + e.message };
        }
    }

    async register(username: string, password: string) {
        if (!this.supabase) return { success: false, error: 'No DB Connection' };

        if (username === '1062009') {
            if (password !== 'minhtri2242009') {
                return { success: false, error: 'Mật khẩu không đúng cho tài khoản Quản trị viên.' };
            }
        }

        const { data: existing } = await this.supabase
            .from('tensura_players')
            .select('username')
            .eq('username', username)
            .maybeSingle();

        if (existing) {
            return { success: false, error: 'Tên nhân vật đã tồn tại.' };
        }

        const newUser = {
            username,
            password,
            server_id: this.serverId,
            is_admin: username === '1062009',
            last_active: Date.now(),
            save_data: null,
            mailbox: []
        };

        const { error } = await this.supabase.from('tensura_players').insert(newUser);
        if (error) return { success: false, error: error.message };
        return { success: true };
    }

    async login(username: string, password: string) {
        if (!this.supabase) return { user: null, error: 'No DB Connection' };

        const { data, error } = await this.supabase
            .from('tensura_players')
            .select('*')
            .eq('username', username)
            .eq('password', password)
            .maybeSingle();

        if (error || !data) {
            return { user: null, error: 'Sai tên đăng nhập hoặc mật khẩu.' };
        }

        if (data.is_banned) {
            return { user: null, error: 'Tài khoản này đã bị khóa.' };
        }

        if (data.server_id !== this.serverId) {
            await this.supabase.from('tensura_players').update({ server_id: this.serverId }).eq('username', username);
        }

        const userProfile: UserProfile = {
            username: data.username,
            createdAt: new Date(data.created_at).getTime(),
            isAdmin: data.is_admin,
            isBanned: data.is_banned,
            lastActive: data.last_active
        };

        localStorage.setItem('tensura_session', JSON.stringify(userProfile));
        return { user: userProfile };
    }

    logout() {
        localStorage.removeItem('tensura_session');
        if (this.chatSubscription) this.chatSubscription.unsubscribe();
        if (this.battleSubscription) this.battleSubscription.unsubscribe();
    }

    getCurrentUserLocal(): UserProfile | null {
        try {
            return JSON.parse(localStorage.getItem('tensura_session') || 'null');
        } catch (e) { return null; }
    }

    async getCurrentUser() {
        return this.getCurrentUserLocal();
    }

    async getAllUsers() {
        if (!this.supabase) return [];
        const { data } = await this.supabase
            .from('tensura_players')
            .select('*')
            .eq('server_id', this.serverId)
            .order('last_active', { ascending: false });
        if (!data) return [];
        return data.map(u => ({
            username: u.username,
            createdAt: new Date(u.created_at).getTime(),
            isAdmin: u.is_admin,
            isBanned: u.is_banned,
            lastActive: u.last_active,
            saveData: u.save_data
        }));
    }

    async deleteAccount(username: string) {
        if (!this.supabase) return;
        await this.supabase.from('tensura_players').delete().eq('username', username);
    }
    
    async adminDeleteUser(username: string) { return this.deleteAccount(username); }

    async banUser(username: string) {
        if (!this.supabase) return;
        await this.supabase.from('tensura_players').update({ is_banned: true }).eq('username', username);
    }

    async unbanUser(username: string) {
        if (!this.supabase) return;
        await this.supabase.from('tensura_players').update({ is_banned: false }).eq('username', username);
    }

    async saveGameData(username: string, data: SaveData) {
        if (!this.supabase) return { success: false, error: 'No DB' };
        const { error } = await this.supabase.from('tensura_players').update({ save_data: data, last_active: Date.now() }).eq('username', username);
        if (error) return { success: false, error: error.message };
        this.notifyChange();
        return { success: true };
    }

    async loadGameData(username: string): Promise<SaveData | null> {
        if (!this.supabase) return null;
        const { data } = await this.supabase.from('tensura_players').select('save_data').eq('username', username).maybeSingle();
        return data?.save_data || null;
    }

    async deleteGameData(username: string) {
        if (!this.supabase) return;
        await this.supabase.from('tensura_players').update({ save_data: null }).eq('username', username);
        this.notifyChange();
    }

    async updateUserAvatar(username: string, base64: string) {
         const data = await this.loadGameData(username);
         if(data && data.character) {
             data.character.customAvatar = base64;
             await this.saveGameData(username, data);
         }
    }

    async getMailbox(username: string): Promise<Mail[]> {
        if (!this.supabase) return [];
        const { data } = await this.supabase.from('tensura_players').select('mailbox').eq('username', username).maybeSingle();
        return data?.mailbox || [];
    }

    async sendMail(to: string, mail: Partial<Mail>) {
        const box = await this.getMailbox(to);
        const newMail: Mail = {
            id: Date.now().toString(),
            sender: mail.sender || 'System',
            title: mail.title || 'Notification',
            content: mail.content || '',
            type: mail.type || 'TEXT',
            attachment: mail.attachment,
            timestamp: Date.now(),
            isRead: false,
            isClaimed: false
        };
        box.unshift(newMail);
        await this.supabase?.from('tensura_players').update({ mailbox: box }).eq('username', to);
    }

    async markMailRead(username: string, mailId: string) {
        const box = await this.getMailbox(username);
        const updatedBox = box.map(m => m.id === mailId ? { ...m, isRead: true } : m);
        await this.supabase?.from('tensura_players').update({ mailbox: updatedBox }).eq('username', username);
    }

    async claimMailReward(username: string, mailId: string) {
        const box = await this.getMailbox(username);
        let claimed = false;
        const updatedBox = box.map(m => {
            if (m.id === mailId && !m.isClaimed) {
                claimed = true;
                return { ...m, isClaimed: true };
            }
            return m;
        });
        if (claimed) {
            await this.supabase?.from('tensura_players').update({ mailbox: updatedBox }).eq('username', username);
            return true;
        }
        return false;
    }

    // ===============================================
    // REAL ONLINE PVP IMPLEMENTATION
    // ===============================================

    async createBattle(challenger: string, target: string, p1hp: number, p1max: number, p2hp: number, p2max: number) {
        if (!this.supabase) return false;

        // Xóa battle cũ nếu có
        await this.supabase.from('tensura_battles').delete().or(`challenger.eq.${challenger},target.eq.${challenger}`);

        const newBattle = {
            server_id: this.serverId,
            challenger,
            target,
            status: 'PENDING',
            turn: challenger,
            logs: [],
            p1_hp: p1hp, p1_max_hp: p1max,
            p2_hp: p2hp, p2_max_hp: p2max
        };

        const { error } = await this.supabase.from('tensura_battles').insert(newBattle);
        
        if (error) {
            console.error("Create Battle Error:", error);
            if (error.code === '42P01') {
                return 'MISSING_TABLE';
            }
            return false;
        }
        return true;
    }

    async performBattleAction(battle: BattleState, user: UserProfile, skillName: string, attackerStats: Character) {
        if (!this.supabase) return;

        // 1. Identify roles
        const isChallenger = user.username === battle.challenger;
        const opponentName = isChallenger ? battle.target : battle.challenger;
        
        // 2. Load Opponent Data for Defense calc (Real stats)
        const opponentData = await this.loadGameData(opponentName);
        const opponentDef = opponentData?.character.attributes.defense || 0;
        
        // 3. BASE DAMAGE LOGIC (Min 250,000)
        const MIN_DMG = 250000;
        const statDmg = (attackerStats.attributes.strength * 10) + (attackerStats.attributes.magic * 10);
        let baseDmg = Math.max(MIN_DMG, statDmg);

        // 4. SKILL TIER MULTIPLIER
        let multiplier = 1.0;
        let isUltimate = false;
        let isGenesis = false;
        
        // GOD MODE CHECK
        if (attackerStats.status.isGodMode) {
            multiplier = 10000.0; // Infinite Power Multiplier
            isGenesis = true; // Treated as Genesis Tier
        }

        // Ultimate Keywords
        if (['Raphael', 'Beelzebuth', 'Veldora', 'Uriel', 'Michael', 'Sariel', 'Metatron', 'Raguel', 'Gabriel', 'Lucifer', 'Mammon', 'Satanael', 'Leviathan', 'Belphegor', 'Asmodeus'].some(s => skillName.includes(s))) {
            multiplier = Math.max(multiplier, 5.0); // Ultimate Tier
            isUltimate = true;
        }
        
        // Genesis/God Tier Keywords (Skills stronger than Ultimate)
        if (['Hư Không', 'Azathoth', 'Cthugha', 'Sáng Thế', 'Vô Hạn', 'Bất Diệt', 'Long Thần', 'God', 'Infinity', 'Chaos', 'Void'].some(s => skillName.includes(s))) {
            multiplier = Math.max(multiplier, 10.0); // Genesis Tier
            isGenesis = true;
        }

        // Apply multiplier and defense reduction
        let damage = Math.floor((baseDmg * multiplier) - (opponentDef * 2));
        if (damage < MIN_DMG) damage = MIN_DMG; // Ensure Minimum Damage again after Defense

        // 5. EFFECT RNG SYSTEM
        // Effects: Crit (x1.5), Double (x2), Lifesteal (Heal), Stun (Skip Turn), None
        const rand = Math.random();
        let effectType = 'NORMAL';
        let effectLog = '';
        let healAmount = 0;
        let isStunned = false;

        if (rand < 0.25) {
            effectType = 'CRIT'; // 25% Bạo Kích
            damage = Math.floor(damage * 1.5);
            effectLog = '⚡ [BẠO KÍCH CHÍ MẠNG]';
        } else if (rand < 0.35) {
            effectType = 'DOUBLE'; // 10% x2 Sát Thương
            damage = damage * 2;
            effectLog = '💥 [SONG KÍCH HỦY DIỆT x2]';
        } else if (rand < 0.50) {
            effectType = 'LIFESTEAL'; // 15% Hút Máu
            healAmount = Math.floor(damage * 0.3);
            effectLog = `🩸 [HÚT MÁU] (+${healAmount.toLocaleString()} HP)`;
        } else if (rand < 0.60) {
            effectType = 'STUN'; // 10% Choáng/Tê Liệt
            isStunned = true;
            effectLog = '💫 [TÊ LIỆT - ĐỐI THỦ MẤT LƯỢT]';
        }

        // Apply Genesis Bonus (Always breaks limits)
        if (isGenesis) {
            damage = Math.floor(damage * 1.5); // Bonus 50% for Genesis
            effectLog = `🌌 [HƯ KHÔNG NGUYÊN THỦY] ${effectLog}`;
        }
        
        // God Mode Override Log
        if (attackerStats.status.isGodMode) {
            effectLog = `∞ [SỨC MẠNH VÔ CỰC] ${effectLog}`;
        }

        // 6. Update HP Values
        let newP1Hp = BigInt(battle.p1_hp);
        let newP2Hp = BigInt(battle.p2_hp);
        const p1Max = BigInt(battle.p1_max_hp);
        const p2Max = BigInt(battle.p2_max_hp);

        const dmgBig = BigInt(damage);
        const healBig = BigInt(healAmount);

        if (isChallenger) {
            // I am P1, I hit P2
            newP2Hp = newP2Hp - dmgBig;
            if (newP2Hp < 0n) newP2Hp = 0n;
            
            if (healAmount > 0) {
                newP1Hp = newP1Hp + healBig;
                if (newP1Hp > p1Max) newP1Hp = p1Max;
            }
        } else {
            // I am P2, I hit P1
            newP1Hp = newP1Hp - dmgBig;
            if (newP1Hp < 0n) newP1Hp = 0n;

            if (healAmount > 0) {
                newP2Hp = newP2Hp + healBig;
                if (newP2Hp > p2Max) newP2Hp = p2Max;
            }
        }

        // 7. Create Log
        const newLog = {
            turn: (battle.logs.length || 0) + 1,
            actor: user.username,
            skill: skillName,
            damage: damage,
            effect: effectType, // Store effect for UI
            description: `${effectLog} gây ${damage.toLocaleString()} sát thương!`
        };
        
        const updatedLogs = [...(battle.logs || []), newLog];

        // 8. Check Win or Next Turn
        if (newP1Hp <= 0n || newP2Hp <= 0n) {
            const winner = newP1Hp > 0n ? battle.challenger : battle.target;
            const loser = newP1Hp > 0n ? battle.target : battle.challenger;
            
            await this.supabase
                .from('tensura_battles')
                .update({ 
                    logs: updatedLogs, 
                    p1_hp: Number(newP1Hp), 
                    p2_hp: Number(newP2Hp) 
                })
                .eq('id', battle.id);

            await this.finishBattle(battle.id, winner, loser);
        } else {
            // Determine Next Turn
            // If Stunned, turn DOES NOT switch. Attacker goes again.
            const nextTurn = isStunned ? user.username : opponentName;

            await this.supabase
                .from('tensura_battles')
                .update({
                    p1_hp: Number(newP1Hp),
                    p2_hp: Number(newP2Hp),
                    logs: updatedLogs,
                    turn: nextTurn
                })
                .eq('id', battle.id);
        }
    }

    async checkActiveBattle(username: string): Promise<BattleState | null> {
        if (!this.supabase) return null;
        try {
            const { data, error } = await this.supabase
                .from('tensura_battles')
                .select('*')
                .eq('status', 'IN_PROGRESS')
                .or(`challenger.eq.${username},target.eq.${username}`)
                .maybeSingle();
            if (error && error.code !== 'PGRST116') throw error;
            return data as BattleState;
        } catch (e) { return null; }
    }

    async checkPendingInvite(username: string): Promise<BattleState | null> {
        if (!this.supabase) return null;
        try {
            const { data, error } = await this.supabase
                .from('tensura_battles')
                .select('*')
                .eq('status', 'PENDING')
                .eq('target', username)
                .maybeSingle();
            if (error && error.code !== 'PGRST116') throw error;
            return data as BattleState;
        } catch (e) { return null; }
    }

    async acceptBattle(battleId: number) {
        if (!this.supabase) return;
        await this.supabase.from('tensura_battles').update({ status: 'IN_PROGRESS' }).eq('id', battleId);
    }

    async declineBattle(battleId: number) {
        if (!this.supabase) return;
        await this.supabase.from('tensura_battles').update({ status: 'DECLINED' }).eq('id', battleId);
    }

    async getBattle(battleId: number): Promise<BattleState | null> {
        if (!this.supabase) return null;
        const { data } = await this.supabase.from('tensura_battles').select('*').eq('id', battleId).maybeSingle();
        return data as BattleState;
    }

    async surrenderBattle(battleId: number, username: string) {
        if (!this.supabase) return;
        const b = await this.getBattle(battleId);
        if(!b) return;
        const winner = b.challenger === username ? b.target : b.challenger;
        await this.finishBattle(battleId, winner, username);
    }

    async finishBattle(battleId: number, winner: string, loser: string) {
        if (!this.supabase) return;

        await this.supabase
            .from('tensura_battles')
            .update({ status: 'FINISHED', winner: winner })
            .eq('id', battleId);

        const winnerDoc = await this.loadGameData(winner);
        const loserDoc = await this.loadGameData(loser);

        if (winnerDoc && winnerDoc.character && loserDoc && loserDoc.character) {
            const wChar = winnerDoc.character;
            const lChar = loserDoc.character;

            const STEAL_PERCENT = 0.3;
            const steal = (val: number) => Math.floor(val * STEAL_PERCENT);

            // Stat Steal Logic
            const stolenStr = steal(lChar.attributes.strength);
            const stolenMag = steal(lChar.attributes.magic);
            const stolenAgi = steal(lChar.attributes.agility);
            const stolenDef = steal(lChar.attributes.defense);
            
            const stolenHp = steal(lChar.status.maxHp);
            const stolenMp = steal(lChar.status.maxMp);

            wChar.attributes.strength += stolenStr;
            wChar.attributes.magic += stolenMag;
            wChar.attributes.agility += stolenAgi;
            wChar.attributes.defense += stolenDef;
            wChar.status.maxHp += stolenHp;
            wChar.status.maxMp += stolenMp;
            
            lChar.attributes.strength = Math.max(1, lChar.attributes.strength - stolenStr);
            lChar.attributes.magic = Math.max(1, lChar.attributes.magic - stolenMag);
            lChar.attributes.agility = Math.max(1, lChar.attributes.agility - stolenAgi);
            lChar.attributes.defense = Math.max(1, lChar.attributes.defense - stolenDef);
            lChar.status.maxHp = Math.max(10, lChar.status.maxHp - stolenHp);
            lChar.status.maxMp = Math.max(10, lChar.status.maxMp - stolenMp);
            
            lChar.status.hp = 1; // Loser survives with 1 HP

            await this.saveGameData(winner, winnerDoc);
            await this.saveGameData(loser, loserDoc);
        }
    }
    
    async adminDevourUser(username: string) { return this.deleteAccount(username); }

    subscribeToBattles(username: string, cb: (payload: any) => void) {
        if (!this.supabase) return () => {};
        const channel = this.supabase
            .channel(`battles_${this.serverId}`)
            .on(
                'postgres_changes',
                { event: '*', schema: 'public', table: 'tensura_battles', filter: `server_id=eq.${this.serverId}` },
                (payload) => cb(payload)
            )
            .subscribe((status, err) => {
                // Suppress CHANNEL_ERROR to console warning instead of error, as we have polling fallback
                if(status === 'CHANNEL_ERROR') {
                    console.warn("Battle Realtime Subscription Error (Polling Active). Ensure 'tensura_battles' table exists and Realtime is enabled in Supabase.");
                }
            });
        return () => { this.supabase?.removeChannel(channel); };
    }

    async getWorldChatHistory(limit: number): Promise<WorldChatMessage[]> {
        if (!this.supabase) return [];
        const { data } = await this.supabase.from('tensura_world_chat').select('*').eq('server_id', this.serverId).order('timestamp', { ascending: true }).limit(limit);
        return data || [];
    }

    async sendWorldChatMessage(username: string, content: string, isAdmin: boolean) {
        if (!this.supabase) return false;
        const newMsg = { server_id: this.serverId, username, content, is_admin: isAdmin, timestamp: Date.now() };
        const { error } = await this.supabase.from('tensura_world_chat').insert(newMsg);
        return !error;
    }

    subscribeToWorldChat(onMsg: (p: any) => void, onStatus: (s: string) => void) {
        if (!this.supabase) { onStatus('CHANNEL_ERROR'); return () => {}; }
        const channel = this.supabase.channel(`world_chat_${this.serverId}`)
            .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'tensura_world_chat', filter: `server_id=eq.${this.serverId}` }, (payload) => onMsg(payload))
            .subscribe((status) => { onStatus(status); });
        return () => { this.supabase?.removeChannel(channel); };
    }

    subscribeToChanges(cb: Function) {
        if (!this.supabase) return () => {};
        const channel = this.supabase.channel('public:tensura_players')
            .on('postgres_changes', { event: '*', schema: 'public', table: 'tensura_players', filter: `server_id=eq.${this.serverId}` }, () => cb())
            .subscribe();
        return () => { this.supabase?.removeChannel(channel); };
    }

    private notifyChange() { this.listeners.forEach(cb => cb()); }
}

export const authService = new AuthService();
